/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Ecdsa', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Ecdsa__factory>
getContractFactory(name: 'Frost', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Frost__factory>
getContractFactory(name: 'Schnorr', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Schnorr__factory>
getContractFactory(name: 'SchnorrSECP256K1', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SchnorrSECP256K1__factory>

  getContractAt(name: 'Ecdsa', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Ecdsa>
getContractAt(name: 'Frost', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Frost>
getContractAt(name: 'Schnorr', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Schnorr>
getContractAt(name: 'SchnorrSECP256K1', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SchnorrSECP256K1>

  deployContract(name: 'Ecdsa', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Ecdsa>
deployContract(name: 'Frost', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Frost>
deployContract(name: 'Schnorr', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Schnorr>
deployContract(name: 'SchnorrSECP256K1', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SchnorrSECP256K1>

  deployContract(name: 'Ecdsa', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Ecdsa>
deployContract(name: 'Frost', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Frost>
deployContract(name: 'Schnorr', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Schnorr>
deployContract(name: 'SchnorrSECP256K1', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SchnorrSECP256K1>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  