/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SchnorrSECP256K1Interface extends Interface {
    getFunction(nameOrSignature: "HALF_Q" | "Q" | "measureVerify" | "verifySignature"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'HALF_Q', values?: undefined): string;
encodeFunctionData(functionFragment: 'Q', values?: undefined): string;
encodeFunctionData(functionFragment: 'measureVerify', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'verifySignature', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'HALF_Q', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'Q', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'measureVerify', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifySignature', data: BytesLike): Result;
  }

  

  export interface SchnorrSECP256K1 extends BaseContract {
    
    connect(runner?: ContractRunner | null): SchnorrSECP256K1;
    waitForDeployment(): Promise<this>;

    interface: SchnorrSECP256K1Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    HALF_Q: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    Q: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    measureVerify: TypedContractMethod<
      [signingPubKeyX: BigNumberish, pubKeyYParity: BigNumberish, signature: BigNumberish, msgHash: BigNumberish, nonceTimesGeneratorAddress: AddressLike, ],
      [[bigint, bigint] & {cold: bigint, warm: bigint }],
      'nonpayable'
    >
    

    
    verifySignature: TypedContractMethod<
      [signingPubKeyX: BigNumberish, pubKeyYParity: BigNumberish, signature: BigNumberish, msgHash: BigNumberish, nonceTimesGeneratorAddress: AddressLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'HALF_Q'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'Q'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'measureVerify'): TypedContractMethod<
      [signingPubKeyX: BigNumberish, pubKeyYParity: BigNumberish, signature: BigNumberish, msgHash: BigNumberish, nonceTimesGeneratorAddress: AddressLike, ],
      [[bigint, bigint] & {cold: bigint, warm: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifySignature'): TypedContractMethod<
      [signingPubKeyX: BigNumberish, pubKeyYParity: BigNumberish, signature: BigNumberish, msgHash: BigNumberish, nonceTimesGeneratorAddress: AddressLike, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }