/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SchnorrInterface extends Interface {
    getFunction(nameOrSignature: "Q" | "measureVerify" | "verify"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'Q', values?: undefined): string;
encodeFunctionData(functionFragment: 'measureVerify', values: [BigNumberish, BytesLike, BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'verify', values: [BigNumberish, BytesLike, BytesLike, BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'Q', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'measureVerify', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify', data: BytesLike): Result;
  }

  

  export interface Schnorr extends BaseContract {
    
    connect(runner?: ContractRunner | null): Schnorr;
    waitForDeployment(): Promise<this>;

    interface: SchnorrInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    Q: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    measureVerify: TypedContractMethod<
      [parity: BigNumberish, px: BytesLike, message: BytesLike, e: BytesLike, s: BytesLike, ],
      [[bigint, bigint] & {cold: bigint, warm: bigint }],
      'nonpayable'
    >
    

    
    verify: TypedContractMethod<
      [parity: BigNumberish, px: BytesLike, message: BytesLike, e: BytesLike, s: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'Q'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'measureVerify'): TypedContractMethod<
      [parity: BigNumberish, px: BytesLike, message: BytesLike, e: BytesLike, s: BytesLike, ],
      [[bigint, bigint] & {cold: bigint, warm: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verify'): TypedContractMethod<
      [parity: BigNumberish, px: BytesLike, message: BytesLike, e: BytesLike, s: BytesLike, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }